version: "3.3"

# Notes: Build - Location of the dockerfile relative to this docker-compose.yml that contains instructions for building teh container
# ports - connects a port locally to the port on the container 
# volumes - 'syncs' a folder on the local machine to a directory in the container
# entrypoint - something i cant get to work yet :(

services:
  angular-frontend:
    build: './angular-src'
    ports:
    - "4200:4200"
    - "49153:49153"
    networks:
    - backend
    volumes:
    - ./angular-src:/angular-src
    # entrypoint: "/home/node/webapp/scripts/entrypoint.sh"

  api-server:
    build: './api-src'
    ports:
    - "3000:3000"
    networks:
    - backend
    depends_on:
    - mongo-database
    volumes:
    - ./api-src:/home/node/server
    working_dir: "/home/node/server"
    # entrypoint: "/home/node/server/entrypoint.sh"

  mongo-database:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
    - backend

networks:
  backend: